name: Build Android APK

on:
  workflow_dispatch: # هذا السطر يسمح لك بتشغيل البناء يدوياً بضغطة زر متى شئت

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Bubblewrap
      run: npm install -g @bubblewrap/cli

    - name: Cache Bubblewrap dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bubblewrap
        key: bubblewrap-${{ runner.os }}

    - name: Build APK (Force without prompts)
      run: |
        # الإجابة التلقائية بكلمة مرور (123456) على أي سؤال لإنشاء مفتاح التوقيع
        # وتخطي التحقق من الرابط لتجنب أخطاء 404 الوهمية أثناء البناء
        yes "123456" | bubblewrap build --skipValidation

    - name: Upload APK File
      uses: actions/upload-artifact@v4
      with:
        name: Ghras-App-APK
        path: ./**/*.apk
